[project]
name = "pytorch-distributed-ml-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "requests>=2.34.2",
    "tokenizers>=0.23.2",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
    "tqdm>=4.70.1",
]

[dependency-groups]
dev = [
    "nbstripout>=0.9.1",
]
